# DXVK Tuning Configuration for Autodesk Inventor on Linux
dxgi.syncInterval = 0
d3d11.maxTessFactor = 64
d3d11.samplerAnisotropy = 16
dxvk.enableAsync = true
d3d11.cachedDynamicBuffers = true
d3d11.maxDynamicImageUpdateFrequency = 0
dxgi.maxFrameLatency = 1
